export default {
  // Input Fields (following user's specified order)
  'short-text-input': 'Short Text Input',
  'long-text-input': 'Long Text Input',
  'email-input': 'Email Input',
  'phone-input': 'Phone Input',
  'number-input': 'Number Input',
  'opinion-scale': 'Opinion Scale',
  checkboxes: 'Checkboxes',
  'multi-select': 'Multi Select',
  'single-select': 'Single Select',
  'range-slider': 'Range Slider',
  'currency-input': 'Currency Input',
  'address-input': 'Address Input',
  'ranking-input': 'Ranking Input',
  'randomize-answer': 'Randomize Answers',
  matrix: 'Matrix Questions',
  'link-input': 'Link Input',
  'time-input': 'Time Input',
  'geo-capture': 'Geo Capture',
  'multiple-choice': 'Multiple Choice',
  rating: 'Rating',
  'file-upload': 'File Upload',
  signature: 'Signature',
  'date-picker': 'Date Picker',

  // Layout Elements
  text: 'Text',
  headings: 'Headings',
  'hidden-fields': 'Hidden Fields',

  // Form Settings
  'conditional-logic': 'Conditional Logic',
  calculator: 'Calculation Fields',
  'answer-piping': 'Answer Piping',
  'pre-populate': 'Pre-Populate Forms',
  redirect: 'Redirect After Submission',
  'close-form': 'Close Form Rules',
  'form-analytics': 'Form Analytics',
  'custom-css': 'Custom CSS',
  'form-version-history': 'Form Version History',
  'pdf-generation': 'PDF Generation',
  'custom-domain': 'Custom Domain',
  'link-preview': 'Link Preview',
  'remove-makeform-branding': 'Remove Makeform branding',
  'email-notifications': 'Email notifications',
  'share-setting': 'Share setting',
  'summary-detail': 'Summary details',
  payment: 'Payment',
}
